### ISSUE TITLE
mock uploader

### ISSUE THREAD

**Issue by rcoh** [RTCovid/nyc-ppe#8]
- pick the upload type (inventory, make, sell)
- display a basic delta between what we had / what you're uploading eg. 10 new deliveries
- display errors eg. wrong columns

**Comment by mjacksonw** [comment]
In Figma, but I think this covers the bullets

<img width="1091" alt="Screen Shot 2020-04-11 at 8 42 56 PM" src="https://user-images.githubusercontent.com/69848/79057942-08256200-7c35-11ea-8e02-4fad98e6262a.png">
